export const ROLES = {
  USER: "ROLE_USER",
  VERIFIER: "ROLE_VERIFIER",
  INSTITUTION_ADMIN: "ROLE_INSTITUTION_ADMIN",
  ADMIN: "ROLE_ADMIN",
};

export const ROLE_VALUES = [
  ROLES.USER,
  ROLES.VERIFIER,
  ROLES.INSTITUTION_ADMIN,
  ROLES.ADMIN,
];
